services:
  mirakc:
    image: custom/mirakc
    container_name: mirakc
    init: true
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus:/dev/bus
      - /dev/pxmlt8video0
      - /dev/pxmlt8video1
      - /dev/pxmlt8video2
      - /dev/pxmlt8video3
      - /dev/pxmlt8video4
      - /dev/pxmlt8video5
      - /dev/pxmlt8video6
      - /dev/pxmlt8video7
    ports:
      - 40772:40772
    volumes:
      - mirakc-epg:/var/lib/mirakc/epg
      - ./config.yml:/etc/mirakc/config.yml:ro
      - /mnt/usbhdd/mirakc:/var/lib/mirakc/recording #<----録画先を指定する>
      - miraview-html:/var/www/miraview:ro
    environment:
      TZ: Asia/Tokyo
      RUST_LOG: info
  miraview:
    image: docker.io/mirakc/mirakc:alpine
    container_name: miraview-loader
    restart: "no"
    volumes:
      - miraview-html:/var/www/miraview
    working_dir: /var/www/miraview
    environment:
      MIRAVIEW_VERSION: v0.1.2
    entrypoint: ash
    command: -c "curl -L https://github.com/maeda577/miraview/releases/download/$$MIRAVIEW_VERSION/build.tar.gz | tar -zxvf -"

volumes:
  mirakc-epg:
    name: mirakc_epg
    driver: local
  miraview-html:
    name: miraview_html
    driver: local
